function expandSun(elem){
	document.getElementById("one").classList.toggle("noninfo");
	document.getElementById("two").classList.toggle("noninfo");
	document.getElementById("three").classList.toggle("noninfo");
	document.getElementById("four").classList.toggle("noninfo");
	document.getElementById("six").classList.toggle("noninfo");
	document.getElementById("seven").classList.toggle("noninfo");
	document.getElementById("eight").classList.toggle("noninfo");
	document.getElementById("nine").classList.toggle("noninfo");
	document.getElementById("ten").classList.toggle("noninfo");
	document.getElementById("one").classList.remove("infobox");
	document.getElementById("two").classList.remove("infobox");
	document.getElementById("three").classList.remove("infobox");
	document.getElementById("four").classList.remove("infobox");
	document.getElementById("six").classList.remove("infobox");
	document.getElementById("seven").classList.remove("infobox");
	document.getElementById("eight").classList.remove("infobox");
	document.getElementById("nine").classList.remove("infobox");
	document.getElementById("ten").classList.remove("infobox");
	document.getElementById("zero").classList.toggle("infobox");
	document.getElementById("suntxt").classList.toggle("text-hide");
}

function expandMercury(elem){
	document.getElementById("zero").classList.toggle("noninfo");
	document.getElementById("two").classList.toggle("noninfo");
	document.getElementById("three").classList.toggle("noninfo");
	document.getElementById("four").classList.toggle("noninfo");
	document.getElementById("six").classList.toggle("noninfo");
	document.getElementById("seven").classList.toggle("noninfo");
	document.getElementById("eight").classList.toggle("noninfo");
	document.getElementById("nine").classList.toggle("noninfo");
	document.getElementById("ten").classList.toggle("noninfo");
	document.getElementById("zero").classList.remove("infobox");
	document.getElementById("two").classList.remove("infobox");
	document.getElementById("three").classList.remove("infobox");
	document.getElementById("four").classList.remove("infobox");
	document.getElementById("six").classList.remove("infobox");
	document.getElementById("seven").classList.remove("infobox");
	document.getElementById("eight").classList.remove("infobox");
	document.getElementById("nine").classList.remove("infobox");
	document.getElementById("ten").classList.remove("infobox");	
	document.getElementById("suntxt").classList.add("text-hide");
	document.getElementById("one").classList.toggle("infobox");

}

function expandVenus(elem){
	document.getElementById("zero").classList.toggle("noninfo");
	document.getElementById("one").classList.toggle("noninfo");
	document.getElementById("three").classList.toggle("noninfo");
	document.getElementById("four").classList.toggle("noninfo");
	document.getElementById("six").classList.toggle("noninfo");
	document.getElementById("seven").classList.toggle("noninfo");
	document.getElementById("eight").classList.toggle("noninfo");
	document.getElementById("nine").classList.toggle("noninfo");
	document.getElementById("ten").classList.toggle("noninfo");
	document.getElementById("zero").classList.remove("infobox");
	document.getElementById("one").classList.remove("infobox");
	document.getElementById("three").classList.remove("infobox");
	document.getElementById("four").classList.remove("infobox");
	document.getElementById("six").classList.remove("infobox");
	document.getElementById("seven").classList.remove("infobox");
	document.getElementById("eight").classList.remove("infobox");
	document.getElementById("nine").classList.remove("infobox");
	document.getElementById("ten").classList.remove("infobox");
	document.getElementById("two").classList.toggle("infobox");
}

function expandEarth(elem){
	document.getElementById("zero").classList.toggle("noninfo");
	document.getElementById("one").classList.toggle("noninfo");
	document.getElementById("two").classList.toggle("noninfo");
	document.getElementById("four").classList.toggle("noninfo");
	document.getElementById("six").classList.toggle("noninfo");
	document.getElementById("seven").classList.toggle("noninfo");
	document.getElementById("eight").classList.toggle("noninfo");
	document.getElementById("nine").classList.toggle("noninfo");
	document.getElementById("ten").classList.toggle("noninfo");
	document.getElementById("zero").classList.remove("infobox");
	document.getElementById("one").classList.remove("infobox");
	document.getElementById("two").classList.remove("infobox");
	document.getElementById("four").classList.remove("infobox");
	document.getElementById("six").classList.remove("infobox");
	document.getElementById("seven").classList.remove("infobox");
	document.getElementById("eight").classList.remove("infobox");
	document.getElementById("nine").classList.remove("infobox");
	document.getElementById("ten").classList.remove("infobox");
	document.getElementById("three").classList.toggle("infobox");
}

function expandMars(elem){
	document.getElementById("zero").classList.toggle("noninfo");
	document.getElementById("one").classList.toggle("noninfo");
	document.getElementById("two").classList.toggle("noninfo");
	document.getElementById("three").classList.toggle("noninfo");
	document.getElementById("six").classList.toggle("noninfo");
	document.getElementById("seven").classList.toggle("noninfo");
	document.getElementById("eight").classList.toggle("noninfo");
	document.getElementById("nine").classList.toggle("noninfo");
	document.getElementById("ten").classList.toggle("noninfo");
	document.getElementById("zero").classList.remove("infobox");
	document.getElementById("one").classList.remove("infobox");
	document.getElementById("two").classList.remove("infobox");
	document.getElementById("three").classList.remove("infobox");
	document.getElementById("six").classList.remove("infobox");
	document.getElementById("seven").classList.remove("infobox");
	document.getElementById("eight").classList.remove("infobox");
	document.getElementById("nine").classList.remove("infobox");
	document.getElementById("ten").classList.remove("infobox");
	document.getElementById("four").classList.toggle("infobox");
}

function expandJupiter(elem){
	document.getElementById("zero").classList.toggle("noninfo");
	document.getElementById("one").classList.toggle("noninfo");
	document.getElementById("two").classList.toggle("noninfo");
	document.getElementById("three").classList.toggle("noninfo");
	document.getElementById("four").classList.toggle("noninfo");
	document.getElementById("seven").classList.toggle("noninfo");
	document.getElementById("eight").classList.toggle("noninfo");
	document.getElementById("nine").classList.toggle("noninfo");
	document.getElementById("ten").classList.toggle("noninfo");
	document.getElementById("zero").classList.remove("infobox");
	document.getElementById("one").classList.remove("infobox");
	document.getElementById("two").classList.remove("infobox");
	document.getElementById("three").classList.remove("infobox");
	document.getElementById("four").classList.remove("infobox");
	document.getElementById("seven").classList.remove("infobox");
	document.getElementById("eight").classList.remove("infobox");
	document.getElementById("nine").classList.remove("infobox");
	document.getElementById("ten").classList.remove("infobox");
	document.getElementById("six").classList.toggle("infobox");
}

function expandSaturn(elem){
	document.getElementById("zero").classList.toggle("noninfo");
	document.getElementById("one").classList.toggle("noninfo");
	document.getElementById("two").classList.toggle("noninfo");
	document.getElementById("three").classList.toggle("noninfo");
	document.getElementById("four").classList.toggle("noninfo");
	document.getElementById("six").classList.toggle("noninfo");
	document.getElementById("eight").classList.toggle("noninfo");
	document.getElementById("nine").classList.toggle("noninfo");
	document.getElementById("ten").classList.toggle("noninfo");
	document.getElementById("zero").classList.remove("infobox");
	document.getElementById("one").classList.remove("infobox");
	document.getElementById("two").classList.remove("infobox");
	document.getElementById("three").classList.remove("infobox");
	document.getElementById("four").classList.remove("infobox");
	document.getElementById("six").classList.remove("infobox");
	document.getElementById("eight").classList.remove("infobox");
	document.getElementById("nine").classList.remove("infobox");
	document.getElementById("ten").classList.remove("infobox");
	document.getElementById("seven").classList.toggle("infobox");
}

function expandUranus(elem){
	document.getElementById("zero").classList.toggle("noninfo");
	document.getElementById("one").classList.toggle("noninfo");
	document.getElementById("two").classList.toggle("noninfo");
	document.getElementById("three").classList.toggle("noninfo");
	document.getElementById("four").classList.toggle("noninfo");
	document.getElementById("six").classList.toggle("noninfo");
	document.getElementById("seven").classList.toggle("noninfo");
	document.getElementById("nine").classList.toggle("noninfo");
	document.getElementById("ten").classList.toggle("noninfo");
	document.getElementById("zero").classList.remove("infobox");
	document.getElementById("one").classList.remove("infobox");
	document.getElementById("two").classList.remove("infobox");
	document.getElementById("three").classList.remove("infobox");
	document.getElementById("four").classList.remove("infobox");
	document.getElementById("six").classList.remove("infobox");
	document.getElementById("seven").classList.remove("infobox");
	document.getElementById("nine").classList.remove("infobox");
	document.getElementById("ten").classList.remove("infobox");
	document.getElementById("eight").classList.toggle("infobox");
}

function expandNeptune(elem){
	document.getElementById("zero").classList.toggle("noninfo");
	document.getElementById("one").classList.toggle("noninfo");
	document.getElementById("two").classList.toggle("noninfo");
	document.getElementById("three").classList.toggle("noninfo");
	document.getElementById("four").classList.toggle("noninfo");
	document.getElementById("six").classList.toggle("noninfo");
	document.getElementById("seven").classList.toggle("noninfo");
	document.getElementById("eight").classList.toggle("noninfo");
	document.getElementById("ten").classList.toggle("noninfo");
	document.getElementById("zero").classList.remove("infobox");
	document.getElementById("one").classList.remove("infobox");
	document.getElementById("two").classList.remove("infobox");
	document.getElementById("three").classList.remove("infobox");
	document.getElementById("four").classList.remove("infobox");
	document.getElementById("six").classList.remove("infobox");
	document.getElementById("seven").classList.remove("infobox");
	document.getElementById("eight").classList.remove("infobox");
	document.getElementById("ten").classList.remove("infobox");
	document.getElementById("nine").classList.toggle("infobox");
}

function expandPluto(elem){
	document.getElementById("zero").classList.toggle("noninfo");
	document.getElementById("one").classList.toggle("noninfo");
	document.getElementById("two").classList.toggle("noninfo");
	document.getElementById("three").classList.toggle("noninfo");
	document.getElementById("four").classList.toggle("noninfo");
	document.getElementById("six").classList.toggle("noninfo");
	document.getElementById("seven").classList.toggle("noninfo");
	document.getElementById("eight").classList.toggle("noninfo");
	document.getElementById("nine").classList.toggle("noninfo");
	document.getElementById("zero").classList.remove("infobox");
	document.getElementById("one").classList.remove("infobox");
	document.getElementById("two").classList.remove("infobox");
	document.getElementById("three").classList.remove("infobox");
	document.getElementById("four").classList.remove("infobox");
	document.getElementById("six").classList.remove("infobox");
	document.getElementById("seven").classList.remove("infobox");
	document.getElementById("eight").classList.remove("infobox");
	document.getElementById("nine").classList.remove("infobox");
	document.getElementById("ten").classList.toggle("infobox");
}
